App\Domain\Model\ManufacturerPaginatedModel:
    attributes:
        manufacturers:
            groups: ['default']
        manufacturersTotal:
            groups: ['default']
        manufacturersPerPage:
            groups: ['default']
        _links:
            groups: ['default']
