App\Domain\Entity\Phone:
    attributes:
        id:
            groups: ['default', 'phone', 'phone_list']
        manufacturer:
            groups: ['phone']
        model:
            groups: ['default', 'phone_list']
        description:
            groups: ['phone']
        price:
            groups: ['phone']
        stock:
            groups: ['phone']
