App\Domain\Model\PhonePaginatedModel:
    attributes:
        phones:
            groups: ['default']
        phonesTotal:
            groups: ['default']
        phonesPerPage:
            groups: ['default']
        _links:
            groups: ['default']
