App\Application\Pagination\PaginatedCollection:
    attributes:
        items:
            groups: ['default', 'phone_list']
        itemsTotal:
            groups: ['default', 'phone_list']
        itemsPerPage:
            groups: ['default', 'phone_list']
        _links:
            groups: ['default', 'phone_list']
