App\Domain\Model\RetailerModel:
    attributes:
        id:
            groups: ['retailer']
        name:
            groups: ['retailer']
        email:
            groups: ['retailer']
        bic:
            groups: ['retailer']
        numberOfClients:
            groups: ['retailer']
