App\Domain\Model\RetailerModel:
    attributes:
        id:
            groups: ['retailer', 'retailer_collection']
        name:
            groups: ['retailer', 'retailer_collection']
        email:
            groups: ['retailer']
        bic:
            groups: ['retailer']
        numberOfClients:
            groups: ['retailer']
        _links:
            groups: ['retailer', 'retailer_collection']
