App\Domain\Model\ManufacturerModel:
    attributes:
        id:
            groups: ['manufacturer']
        name:
            groups: ['manufacturer', 'phone', 'manufacturer_collection']
        phones:
            groups: ['manufacturer']
        tablets:
            groups: ['manufacturer']
        numberOfPhones:
            groups: ['manufacturer_collection']
        numberOfTablets:
            groups: ['manufacturer_collection']
